### ISSUE TITLE
Scelta linguaggio di markup

### ISSUE THREAD

**Issue by davcri** [busmath/SCOP_Guide#1]
Quale linguaggio di markup vogliamo utilizzare per creare questa guida ? Le soluzioni che mi vengono in mente sono:

* __BBCode__ : è comodo da portare sul forum, però è scomodo da modificare ed è un po' limitato.
* __HTML da convertire in BBC__: Potrebbe essere più comodo da modificare e inoltre sarebbe facile da portare su una pagina web. Però non so se i convertitori HTML->BBC funzionino bene.

Opinioni, suggerimenti ?

**Comment by SilvioC90** [comment]
Io proprenderei di più verso l'HTML. Però se va portato sul forum BBCode resta la sola alternativa credo.

**Comment by davcri** [comment]
Oh Silvio ci sei anche tu ! Che bello :smile: 
Sì anche io preferirei l'HTML... tanto a quel punto si potrebbe direttamente mettere un link dal forum alla pagina web.

PS: Comunque scrivere questa guida potrebbe essere un ottimo modo creativo per migliorare la nostra confidenza con git/github !

**Comment by busmath** [comment]
Anche io punterei sull'HTML

**Comment by davcri** [comment]
Ok allora possiamo chiudere quando sarà caricato il primo file :)

**Comment by SilvioC90** [comment]
Mi spiegate brevemente cosa faremo? :)

**Comment by davcri** [comment]
Bella domanda. In pratica amplieremo la guida di Mattia rendendola la guida definitiva per il miglioramento di Skyrim ! 
L'ispirazione del nome è venuta da [__S.T.E.P.__](http://wiki.step-project.com/Main_Page). Noi abbiamo intenzione di fare __S.C.O.P.__ (_Skyrim Complete Overhaul P._) :smile: 

PS: la "P" di SCOP è ancora in fase di determinazione xD se hai qualche idea. spara xD

**Comment by davcri** [comment]
In realtà l'idea di mettere la guida su github mi è venuta perché modificando la guida tramite git, si ha un difflog che è molto comodo per vedere cosa è cambiato tra una revisione e l'altra. Quindi è più facile da leggere e/o migliorare.

**Comment by davcri** [comment]
Chiudo questa issue visto che abbiamo deciso per l'HTML. 
Intanto ho cominciato a fare la conversione sul branch HTML_rewrite: [link al branch](https://github.com/busmath/SCOP_Guide/tree/HTML_rewrite).

Vi ricordo che per lavorare (committare) su un branch diverso dal master dovete: 
```
# 1 - creare un nuovo branch
git branch HTML_rewrite

# 2 - spostarvi sul nuovo branch
git checkout HTML_rewrite

# 3 - collegare il nuovo branch con il reference online: origin/HTML_rewrite
git branch --set-upstream-to origin/HTML_rewrite

# 4 - scaricare in locale i nuovi commit
git pull origin HTML_rewrite
```
Se volete approfondire leggete [questa risposta su stackoverflow.com](http://stackoverflow.com/questions/67699/clone-all-remote-branches-with-git)
Da notare che i passi 1-2-3 possono essere compressi in un unico comando: 
```
git checkout -b HTML_rewrite origin/HTML_rewrite
```

**Comment by davcri** [comment]
Ah una volta chiusa un'issue si può comunque commentare (e all'occorrenza riaprire), l'unica differenza è che non verrà più mostrata quando si va nella sezione _issues_ : https://github.com/busmath/SCOP_Guide/issues
